FROM node:20-alpine

WORKDIR /srv/app

RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 1337

CMD ["npm", "run", "develop"]
